import { defineStore } from "pinia";
import { useStorage } from "@vueuse/core";

export const requestDBStore = defineStore("requestDB", {
  state: () => ({
    allrequest: [
      {
        id: useStorage("request1id", "1"),
        username: useStorage("request1username", ""),
        techname: useStorage("request1techname", ""),
        status: useStorage("request1status", ""),
        devicename: useStorage("request1dname", ""),
        devicebrand: useStorage("request1brand", ""),
        date: useStorage("request1date", ""),
        datefinish: useStorage("request1datefinish", ""),
        price: useStorage("request1price", 0),
        available: useStorage("request1available", true),
      },
      {
        id: useStorage("request2id", "2"),
        username: useStorage("request2username", ""),
        techname: useStorage("request2techname", ""),
        status: useStorage("request2status", ""),
        devicename: useStorage("request2dname", ""),
        devicebrand: useStorage("request2brand", ""),
        date: useStorage("request2date", ""),
        datefinish: useStorage("request2datefinish", ""),
        price: useStorage("request2price", 0),
        available: useStorage("request2available", true),
      },
      {
        id: useStorage("request3id", "3"),
        username: useStorage("request3username", ""),
        techname: useStorage("request3techname", ""),
        status: useStorage("request3status", ""),
        devicename: useStorage("request3dname", ""),
        devicebrand: useStorage("request3brand", ""),
        date: useStorage("request3date", ""),
        datefinish: useStorage("request3datefinish", ""),
        price: useStorage("request3price", 0),
        available: useStorage("request3available", true),
      },
      {
        id: useStorage("request4id", "4"),
        username: useStorage("request4username", ""),
        techname: useStorage("request4techname", ""),
        status: useStorage("request4status", ""),
        devicename: useStorage("request4dname", ""),
        devicebrand: useStorage("request4brand", ""),
        date: useStorage("request4date", ""),
        datefinish: useStorage("request4datefinish", ""),
        price: useStorage("request4price", 0),
        available: useStorage("request4available", true),
      },
      {
        id: useStorage("request5id", "5"),
        username: useStorage("request5username", ""),
        techname: useStorage("request5techname", ""),
        status: useStorage("request5status", ""),
        devicename: useStorage("request5dname", ""),
        devicebrand: useStorage("request5brand", ""),
        date: useStorage("request5date", ""),
        datefinish: useStorage("request5datefinish", ""),
        price: useStorage("request5price", 0),
        available: useStorage("request5available", true),
      },
      {
        id: useStorage("request6id", "6"),
        username: useStorage("request6username", ""),
        techname: useStorage("request6techname", ""),
        status: useStorage("request6status", ""),
        devicename: useStorage("request6dname", ""),
        devicebrand: useStorage("request6brand", ""),
        date: useStorage("request6date", ""),
        datefinish: useStorage("request6datefinish", ""),
        price: useStorage("request6price", 0),
        available: useStorage("request6available", true),
      },
      {
        id: useStorage("request7id", "7"),
        username: useStorage("request7username", ""),
        techname: useStorage("request7techname", ""),
        status: useStorage("request7status", ""),
        devicename: useStorage("request7dname", ""),
        devicebrand: useStorage("request7brand", ""),
        date: useStorage("request7date", ""),
        datefinish: useStorage("request7datefinish", ""),
        price: useStorage("request7price", 0),
        available: useStorage("request7available", true),
      },
      {
        id: useStorage("request8id", "8"),
        username: useStorage("request8username", ""),
        techname: useStorage("request8techname", ""),
        status: useStorage("request8status", ""),
        devicename: useStorage("request8dname", ""),
        devicebrand: useStorage("request8brand", ""),
        date: useStorage("request8date", ""),
        datefinish: useStorage("request8datefinish", ""),
        price: useStorage("request8price", 0),
        available: useStorage("request8available", true),
      },
      {
        id: useStorage("request9id", "9"),
        username: useStorage("request9username", ""),
        techname: useStorage("request9techname", ""),
        status: useStorage("request9status", ""),
        devicename: useStorage("request9dname", ""),
        devicebrand: useStorage("request9brand", ""),
        date: useStorage("request9date", ""),
        datefinish: useStorage("request9datefinish", ""),
        price: useStorage("request9price", 0),
        available: useStorage("request9available", true),
      },
      {
        id: useStorage("request10id", "10"),
        username: useStorage("request10username", ""),
        techname: useStorage("request10techname", ""),
        status: useStorage("request10status", ""),
        devicename: useStorage("request10dname", ""),
        devicebrand: useStorage("request10brand", ""),
        date: useStorage("request10date", ""),
        datefinish: useStorage("request10datefinish", ""),
        price: useStorage("request10price", 0),
        available: useStorage("request10available", true),
      },
    ],
  }),
  getters: {},
  actions: {},
});
