import { defineStore } from "pinia";
import { useStorage } from "@vueuse/core";

export const techDBStore = defineStore("techDB", {
  state: () => ({
    alltech: [
      {
        id: useStorage("tech1id", "1"),
        fullname: useStorage("tech1fullname", "Nicki"),
        email: useStorage("tech1email", "n@g.com"),
        username: useStorage("tech1username", "kgds"),
        userType: useStorage("tech1userType", "technician"),
        password: useStorage("tech1password", "123456"),
        accessToken: useStorage("tech1accessToken", ""),
        available: useStorage("tech1value", false),
        visibility: useStorage("tech1vis", true),
        isLogin: useStorage("tech1isLogin", false),
      },
      {
        id: useStorage("tech2id", "2"),
        fullname: useStorage("tech2fullname", "Big"),
        email: useStorage("tech2email", "big@g.com"),
        username: useStorage("tech2username", "biggy"),
        userType: useStorage("tech2userType", "technician"),
        password: useStorage("tech2password", "123456"),
        accessToken: useStorage("tech2accessToken", ""),
        available: useStorage("tech2value", false),
        visibility: useStorage("tech2vis", true),
        isLogin: useStorage("tech2isLogin", false),
      },
      {
        id: useStorage("tech3id", "3"),
        fullname: useStorage("tech3fullname", "Zetar"),
        email: useStorage("tech3email", "zetar@g.com"),
        username: useStorage("tech3username", "Zetar"),
        userType: useStorage("tech3userType", "technician"),
        password: useStorage("tech3password", "123456"),
        accessToken: useStorage("tech3accessToken", ""),
        available: useStorage("tech3value", false),
        visibility: useStorage("tech3vis", true),
        isLogin: useStorage("tech3isLogin", false),
      },
      {
        id: useStorage("tech4id", "4"),
        fullname: useStorage("tech4fullname", "Pond"),
        email: useStorage("tech4email", "pond@g.com"),
        username: useStorage("tech4username", "Pondy"),
        userType: useStorage("tech4userType", "technician"),
        password: useStorage("tech4password", "123456"),
        accessToken: useStorage("tech4accessToken", ""),
        available: useStorage("tech4value", false),
        visibility: useStorage("tech4vis", true),
        isLogin: useStorage("tech4isLogin", false),
      },
      {
        id: useStorage("tech5id", "5"),
        fullname: useStorage("tech5fullname", ""),
        email: useStorage("tech5email", ""),
        username: useStorage("tech5username", ""),
        userType: useStorage("tech5userType", ""),
        password: useStorage("tech5password", ""),
        accessToken: useStorage("tech5accessToken", ""),
        available: useStorage("tech5value", true),
        visibility: useStorage("tech5vis", false),
        isLogin: useStorage("tech5isLogin", false),
      },
    ],
  }),
  getters: {},
  actions: {},
});
